name: Update README with setup.ps1 Content

on:
  push:
    paths:
      - 'setup.ps1'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README.md
        run: |
          echo '## Setup Script' > README.md
          echo '```powershell' >> README.md
          cat setup.ps1 >> README.md
          echo '```' >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with setup.ps1 content'
          git push
